version: "3.9"

services:
  frontend:
    image: aimablm/flashlearn:frontend-latest  # Replace with your actual tag
    container_name: flashlearn-frontend
    restart: always
    ports:
      - "3050:80"
    networks:
      - flashlearn_net

  backend:
    image: aimablm/flashlearn:backend-latest   # Replace with your actual tag
    container_name: flashlearn-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=
      - JWT_SECRET=
    networks:
      - flashlearn_net

networks:
  flashlearn_net:
    name: flashlearn-internal-net
    driver: bridge
